<?php

namespace AppBundle\Repository;

/**
 * ModulePartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulePartRepository extends \Doctrine\ORM\EntityRepository
{
}
