<?php

namespace AppBundle\Repository;

/**
 * TalentStatusHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentStatusHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
