<?php

namespace AppBundle\Repository;

/**
 * TalentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentRepository extends \Doctrine\ORM\EntityRepository
{
}
